### ISSUE TITLE
-sh: /jffs/sbin/ipset: not found

### ISSUE THREAD

**Issue by laimison** [jamesmacwhite/ipset-r7000-dd-wrt#1] opened 2019-01-15 01:01 UTC
Hey,

Any ideas on this issue?

```
root@DD-WRT:/jffs# /jffs/sbin/ipset 
-sh: /jffs/sbin/ipset: not found
root@DD-WRT:/jffs# ls /jffs/sbin/ipset 
/jffs/sbin/ipset
root@DD-WRT:/jffs#
```
```
root@DD-WRT:/jffs/sbin# ./ipset
-sh: ./ipset: not found
root@DD-WRT:/jffs/sbin# ls -l ipset
-rwxr-xr-x    1 root     root        139984 Nov 27 21:10 ipset
root@DD-WRT:/jffs/sbin#
```

I have tried various ways to add required directories to PATH and LD_LIBRARY_PATH (for lib and sbin) unsuccessfully.

The module is successfully loaded:

```
root@DD-WRT:/jffs# lsmod | grep xt_set
xt_set                  6563  0 
root@DD-WRT:/jffs# 
```

`opkg` is not available in my build

Build information:

```
DD-WRT v3.0-r37015M kongac (09/23/18)
Linux DD-WRT 4.4.157 #603 SMP Sun Sep 23 01:10:11 CEST 2018 armv7l DD-WRT
```
Unit:
Netgear R7000

Many thanks

**Comment by jamesmacwhite** [comment] 2019-01-15 06:35
@laimison Hi there. `opkg` wouldn't be available by default on any build. You'd need to install something like Entware on a USB drive.

https://wiki.dd-wrt.com/wiki/index.php/Installing_Entware

The extracted binaries are provided really as a last resort. You should consider setting up Entware, it's really easy:

I haven't test the stuff in /opt much, because they are just extracted versions of the ipk files.

**Comment by laimison** [comment] 2019-01-15 23:19
Hi James,

Thanks for pointing me out. Appreciated!

Originally, I refused the idea about `opkg` because of possible different build than yours and lack of DD-WRT knowledge.

I managed to get this done successfully!

My router is outside of UK and I do not have USB flash there. So this is the procedure to get `opkg` and `ipset` done using jffs (If you have enough space!)

To share with anyone, I have done these steps:

Enable jffs through web GUI and reboot
```
mkdir /jffs/opt_bind
mount -o bind /jffs/opt_bind /opt
cd /opt
wget http://bin.entware.net/armv7sf-k3.2/installer/generic.sh
sh generic.sh
opkg install /jffs/ipk/dnsmasq-full_2.80test3-2_armv7-3.2.ipk
opkg install /jffs/ipk/ipset_6.34-1_armv7-3.2.ipk
opkg install /jffs/ipk/iptables_1.4.21-2a_armv7-3.2.ipk --force-checksum
insmod /jffs/xt_set.ko
lsmod
```

I found that I have enough space. It's good to run something like `while true; do df -m /opt | grep jffs; sleep 2; done` in another window to make sure you will not fill up the space.

```
root@DD-WRT:/opt/sbin# df -m /opt
Filesystem           1M-blocks      Used Available Use% Mounted on
/dev/mtdblock/5             94         9        85   9% /jffs
root@DD-WRT:/opt/sbin#
```

Quick win to see whether `ipset` worked:
```
root@DD-WRT:/opt/sbin# mount -o bind /opt/sbin/dnsmasq /usr/sbin/dnsmasq
root@DD-WRT:/opt/sbin# mount -o bind /opt/sbin/iptables /usr/sbin/iptables
root@DD-WRT:/opt/sbin# mount -o bind /opt/sbin/ip6tables /usr/sbin/ip6tables
root@DD-WRT:/opt/sbin# iptables --version
iptables v1.4.21
root@DD-WRT:/opt/sbin# ipset --version
ipset v6.34, protocol version: 6
root@DD-WRT:/opt/sbin#
root@DD-WRT:/opt/sbin# ipset -N NETTEST hash:net 
root@DD-WRT:/opt/sbin# ipset -A NETTEST 10.0.0.0/8
root@DD-WRT:/opt/sbin# ipset -L NETTEST
Name: NETTEST
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 376
References: 0
Members:
10.0.0.0/8
root@DD-WRT:/opt/sbin# iptables -A OUTPUT -m set --match-set NETTEST dst -j ACCEPT
root@DD-WRT:/opt/sbin# iptables -L OUTPUT -v | grep NETTEST
    0     0 ACCEPT     all  --  any    any     anywhere             anywhere             match-set NETTEST dst
root@DD-WRT:/opt/sbin# 
```

**Comment by jamesmacwhite** [comment] 2019-01-16 07:16
Nice work! Installing to JFFS directly is certainly an option, if you can't use USB. Thanks for write up. I'll incorporate it into the main info. JFFS is generally my recommended place for stuff like kernel modules because it's a filesystem location available early in the start-up process compared to USB.

One thing I found out recently is large ipset chains and restoring them seem to cause a kernel panic. I didn't have serial console hooked up at the time but I'm going to assume it was likely a memory issue because the restore file had grown quite large. 

Need to add that note too!

**Comment by laimison** [comment] 2019-01-16 09:43
Thanks for mentioning this. My plan is to add all UK subnets. I'm on my phone right now, but there could be a thousand of subnets (approx. guess from my memory). I have the same R7000 at home so will test this first as I'm aware now. Is this caused exactly when you are adding entries to ipset set?

**Comment by jamesmacwhite** [comment] 2019-01-16 10:03
It will be interesting if you could test something like that actually because I haven't had enough time to debug further, but I suspect it's overwhelming the memory on my R7000.

What I do is have script that dumps the contents of the ipset chains to a file periodically using cron. The way this is done is:

```ipset save > /path/to/ipset.rules```

This is written to persistent storage like JFFS or USB with /opt. With a bit of bash scripting you can do a file size comparison against the current ipset rules in memory and determine if the file needs to be updated at various intervals. Within that same script is the reverse, determine if the rules in memory is less than the saved file and if so do a restore. i.e. if the router has been rebooted and the memory cleared.

```ipset restore -! < /path/to/ipset.rules```

`-! <` is used in case you already have the referenced ipset chains within the rules file already initialised, which would error if you tried a simple `restore`. I initialise the ipset chains in my `.rc_startup`, so this avoids that error.

However, more recently this has caused my R7000 to reboot. I have both IPv4 and IPv6 sets enabled and the restore file had grown quite large, I didn't catch the filesize, but I strongly suspect it simply overwhelmed the router.

I did do a single restore of one rule and it worked, so I think ipset itself works and likewise if the package itself was broke I'd of thought initialising chains would crash the router.

**Comment by laimison** [comment] 2019-01-17 11:17
Am I right that your ipset list is growing so this is the reason why you have cron job to update this to persistent storage constantly?

Do you have some 'sleep' before any commands in your `.rc_startup` to make sure you have time to send the SSH command and get out from crashing loop? If so what is your value in seconds?

I'm actually guessing that your router crashes way later than during the startup moment, but at least it's good to add some considerable sleep value.

If I were you and understood the issue, I would replace this in crontab for tracking:

`/usr/bin/free -m > /jffs/memory.log;    ipset restore -! < /path/to/ipset.rules 2>> /jffs/memory.log;    echo 'done' >> /jffs/memory.log`

I'll take a look at this on weekend if any spare time.

**Comment by jamesmacwhite** [comment] 2019-01-17 11:33
Correct. My use case of ipset is basically routing traffic to bypass my VPN connection for certain sites. The main candidates are streaming sites like Netflix, which are hostile to VPN usage. As Netflix operates a lot of CDNs, each stream could in theory use a different server, so the list can get large and Netflix is only one example. Other sites that operate over large CDNs suffer the same ipset bloat, but that is the intended purpose.

Fortunately, I didn't put the ipset restore in my `.rc_startup`, instead it's performed within a Bash script that is scheduled via cron so I have a window of about 15 minutes (scheduled interval) before the router reboots. This became apparent when my R7000 would only stay up for about 15 minutes and then reboot. I narrowed it down to the ipset restore command as running it via SSH triggers the same behaviour.

I think it is the rule set size, I have both a IPv4 and IPv6 ruleset, so its understandable that it can grow quite big, while the R7000 is pretty beefy, I think even with 256 MB of RAM (which is going to be taken partly by the firmware) I'm causing a kernel panic because of lack of memory.

The one thing I could look into if DD-WRT supports a swap partition on USB and see if I can restore a large ipset list with swap, performance wouldn't be great but could prevent a memory limit.

**Comment by laimison** [comment] 2019-01-17 12:02
I see that it's about `ipset restore` command.

I'm able to see `swapon`, `mkswap` and `dd` commands so quite likely you can create and enable a swap file easily. At least it can help to debug an issue.

Anyway, I'll have a look at my set if no issues and get back.

**Comment by laimison** [comment] 2019-01-17 22:03
Hi James,

There is just some information from my observations.

I have tried to add all UK subnets to `hash:net`. At least it didn't crash after adding all entries. There are 7299 of them. Also I can confirm that it consumes 200 KB of memory. Measured this with:

```
root@DD-WRT:/# ipset -L | grep 'Size in memory'
Size in memory: 193688
root@DD-WRT:/# 
```
and also with `free -m`. The free memory is at 212 MB and was the same size before making set (by taking only 200 KB).

A note that I have used another method, which is `while` loop instead of built-in `restore`:

```
root@DD-WRT:/# head -n 3 /jffs/countries/gb.zone 
45.112.4.0/22
103.69.204.0/22
103.73.252.0/22
root@DD-WRT:/# while read -r line; do echo $line; /opt/sbin/ipset -A NETTEST $line; done < gb.zone
```

What I liked that this was considerably fast. It took around 10 seconds to create a set.

**Comment by jamesmacwhite** [comment] 2019-01-17 22:16
Hi.

This is great info, thanks for testing! It might look like the `ipset restore` itself is the problem. I did consider using something like a line feed approach to re-add entries instead. So it doesn't appear to a memory issue after all then, could be the way the rules are restored or maybe there is a incompatibility issue with ipset itself with the DD-WRT kernel. The way it is compiled is a bit hacky and not ideal.

**Comment by laimison** [comment] 2019-01-17 22:52
Yeah, I don't think it will consume more memory even having a real traffic. I can believe that ipset is just a filter and network packets go through this shape, which is not resource eater at all.

Good to hear that this helped in your case as well!

Will report if anything unexpected for a longer run.

These DD-WRT builds look experimental to me as well, but if you found something stable it can work for months if not years without crashes such as `DD-WRT v3.0-r29620M kongac (05/10/16)` with OpenVPN server which I upgraded to `DD-WRT v3.0-r37015M (09/23/18)` with ipset & VPN support included.

What build are you using? Is it fully stable except ipset tools? This is just in case if I will discover that my new build is not stable to keep router abroad.

**Comment by jamesmacwhite** [comment] 2019-01-19 08:33
I currently have `DD-WRT v3.0-r37845M kongac (11/25/18)` deployed and it had 45 days of uptime without issues before I rebooted it manually (for nothing related). Kong builds are generally more stable than the BrainSlayer releases, mainly because Kong targets a smaller subnet of routers which he generally tests on.

**Comment by laimison** [comment] 2019-01-19 18:46
Thanks for useful info. I think this issue is sorted and likely all of those latest Kong builds are fine for IPset.

I use two of R7000 to serve small websites in different locations at 100/100mbps. Obviously, there are servers behind these routers in a cluster.

I know, it's not a professional solution, but luckily it's enough resources for the network traffic. Probably, I need to use something more powerful if any heavier load.

I like DD-WRT and stability, but not sure whether there are some much faster options supported by Kong if any replacement required in the future.

**Comment by jamesmacwhite** [comment] 2019-01-30 22:47
An R7800 would be an upgrade if you were looking for faster options (relatively priced), it is a different SoC (Atheros) though. If you are interested in running a VPN client directly and want decent performance with encryption, it will beat the R7000 hands down, which tops out at about 50 mbps. The processor speed is the main focus point there.

I've reworked my restore process and will leave it in production to see if I can replicate any further crashes I talked about. Your test restore by appending raw IP address data directly with `ipset -A` made me think and rework my script I use. I still use `ipset save` to dump my rules contents, but wrote something similar to this for the restore wrapped in a function, given I have both a v4 and v6 ruleset:

```
ipset_restore()
{
# $1 - Name of ipset chain to restore to
# $2 - Rules file to restore from
while read -r line; do
    IP=$(echo "$line" | awk '{ print $3 }')
    ipset -A "$1" "$IP" &>/dev/null
done < <(tail -n +2 "$2")
}
```
In my case because `ipset save` doesn't just output the IP values in the file, I need to parse the line for the actual IP value when restoring as well as preventing the first line from being read because it looks like this:

```
create BYPASS_VPN_IPV4 hash:ip family inet hashsize 1024 maxelem 65536
add BYPASS_VPN_IPV4 x.x.x.x
add BYPASS_VPN_IPV4 x.x.x.x
...
```

I tested a restore with a sizable amount of IP addresses currently in memory which ran successfully and didn't crash the router this time.

**Closed as completed** 2019-01-31 08:47 UTC

**Comment by laimison** [comment] 2019-02-01 14:55
Yep, it looks the same from system perspective. As I see `ipset save` just reads information and prints to stdout so unlikely it can crash anything. Just for the information to report, my router is running under load through iptables/ipset rules for two weeks without issues.

**Comment by iguy0** [comment] 2019-07-18 13:48
Hi all,

I wanted to shed a bit of light on this issue. Through pain and suffering i managed to get the restore to function to work. 

While is true the kernel memory allocation operations on DD-WRT(maybe OpenWRT too) is causing kernel panic and rebooting the router when using this function. Attempting to load relatively small chunks at a time will NOT cause the crash. Learned this the hard way and arrived to 100 entries at the time as maximum numbers. btw, i have 512mb of ram, after loading all of those(plus everything i have running) i still have 397mb free.

Here is some shell code for testing on a script:
`
# No crashes.
split -l 100 --additional-suffix=.splitset "${tmpdir}/${setname}" "${tmpdir}/"
for splitset in $(ls ${tmpdir}/*.splitset); do
        ipset -R < "${splitset}"
        rm "${splitset}" 2>/dev/null
done
# gawk also too but faster than while/read..
# gawk '{ system("ipset " " " $1 " " $2 " " $3) }' "${tmpdir}/${setname}"
# slow...
# while read -r line; do ipset -A "${setname}" $line; done < "${tmpdir}/${setname}"
# ddwrt ipset crashes router when using restore
# ipset -R <"${tmpdir}/${setname}" || exit 1

$setname format:
-A setname 1.0.132.28
-A setname 1.0.153.145
-A setname 1.0.206.151
`

I hope this will be useful for someone, now i can load 8.000.000+ IPs without waiting 3+ hours..
Thank you for compiling the packages together, i can confirm is working for the latest 4.4 kernel on Netgear r8500

Best regards.

OBS: How do i fix this text formatting?... lol
